name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     apt update
    #     apt install -y clang build-essential

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Build 
      run: uv build

    - name: Test with pytest
      run: uv run pytest
